### ISSUE TITLE
newest game/editor version not working??

### ISSUE THREAD

**Issue by demir-pl** [SkiTles55/SPT-AKI-Profile-Editor#50]
**Versions**
- SPT-AKI Server version  -  3.3.0 (in the server file says SPT-AKI 3.4.0?)
- SPT-AKI Profile Editor version  -  2.4.2
- List of installed mods  -  none

**Describe the bug**
after creating a new profile and trying to edit it (after one raid) it gives two long errors (see pictures) and closes.
i tried reinstaling aki and the editor but everything seems fine. **basically doesn't work**

**Additional context**
SPT-AKI Profile file - no nee to (happend right after creating new one)

**Additional info**
in the errors i see that it wants to source/take stuff from disk D:/ (i only have one disk) and tries to pull stuff from none existing folders?

![image](https://user-images.githubusercontent.com/89728477/208787903-10b0ab8f-908d-416f-8253-b707b828b63f.png)

![image](https://user-images.githubusercontent.com/89728477/208787941-b0afa9fc-63a9-4825-a342-e7d9a5244f3c.png)

**Comment by ChiNoel-osu** [comment]
Same issue
<details><summary>Log</summary>
<p>
2022/12/21 2:51:21 PM: ServerDatabase LocalesGlobal (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\locales\global\en.json) loading error: Error converting value "TRADING" to type 'System.Collections.Generic.Dictionary`2[System.String,SPT_AKI_Profile_Editor.Core.ServerClasses.LocalesGlobalTrading]'. Path 'Trading', line 9218, position 22.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\assault.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\bear.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\bossbully.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\bossgluhar.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\bosskilla.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\bossknight.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\bosskojaniy.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\bosssanitar.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\bosstagilla.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\cursedassault.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\exusec.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\followerbigpipe.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\followerbirdeye.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\followerbully.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\followergluharassault.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\followergluharscout.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\followergluharsecurity.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\followerkojaniy.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\followersanitar.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\gifter.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\marksman.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\pmcbot.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\sectantpriest.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\sectantwarrior.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase BotType (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\bots\types\usec.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:21 PM: ServerDatabase ItemsDB (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\templates\items.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:22 PM: ServerDatabase Handbook (V:\Escape From Tarkov - Aki\Client.0.12.12.32.20765\Aki_Data\Server\database\templates\handbook.json) loading error: Object reference not set to an instance of an object.
2022/12/21 2:51:22 PM: ServerDatabase HandbookHelper loading error: Value cannot be null. (Parameter 'source')
2022/12/21 2:51:22 PM: Exception Message: Object reference not set to an instance of an object.. | StackTrace:    at SPT_AKI_Profile_Editor.Core.ProfileClasses.Character.<>c.<get_ExaminedItems>b__43_0(KeyValuePair`2 x) in D:\GitHubRepos\SPT-AKI-Profile-Editor\SPT-AKI Profile Editor\Core\ProfileClasses\Character.cs:line 152
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at MS.Internal.Data.EnumerableCollectionView.LoadSnapshotCore(IEnumerable source)
   at MS.Internal.Data.EnumerableCollectionView..ctor(IEnumerable source)
   at MS.Internal.Data.ViewManager.GetViewRecord(Object collection, CollectionViewSource cvs, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
   at MS.Internal.Data.DataBindEngine.GetViewRecord(Object collection, CollectionViewSource key, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
   at System.Windows.Data.CollectionViewSource.EnsureView(Object source, Type collectionViewType)
   at System.Windows.Data.CollectionViewSource.EnsureView()
   at System.Windows.Data.CollectionViewSource.OnSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2022/12/21 2:51:23 PM: No updates available
2022/12/21 2:51:26 PM: Exception Message: Object reference not set to an instance of an object.. | StackTrace:    at SPT_AKI_Profile_Editor.Core.ProfileClasses.Character.<>c.<get_ExaminedItems>b__43_0(KeyValuePair`2 x) in D:\GitHubRepos\SPT-AKI-Profile-Editor\SPT-AKI Profile Editor\Core\ProfileClasses\Character.cs:line 152
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at MS.Internal.Data.EnumerableCollectionView.LoadSnapshotCore(IEnumerable source)
   at MS.Internal.Data.EnumerableCollectionView..ctor(IEnumerable source)
   at MS.Internal.Data.ViewManager.GetViewRecord(Object collection, CollectionViewSource cvs, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
   at MS.Internal.Data.DataBindEngine.GetViewRecord(Object collection, CollectionViewSource key, Type collectionViewType, Boolean createView, Func`2 GetSourceItem)
   at System.Windows.Data.CollectionViewSource.EnsureView(Object source, Type collectionViewType)
   at System.Windows.Data.CollectionViewSource.EnsureView()
   at System.Windows.Data.CollectionViewSource.OnSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at SPT_AKI_Profile_Editor.App.Main()
</p>
</details>

**Comment by SkiTles55** [comment]
Compatibility with 3.4.0 not tested.
Bug related to user profile. No attached profile file in report.

**Comment by SkiTles55** [comment]
UPD: Currentprofile editor version not working with 3.4.0

**Comment by demir-pl** [comment]
> Compatibility with 3.4.0 not tested. Bug related to user profile. No attached profile file in report.

the not working profile you wanted:
[17603f97c148283e55007f96.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10279079/17603f97c148283e55007f96.zip)


> UPD: Current profile editor version not working with 3.4.0

so i understand we just wait for the update?
